# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 780009fb1c85d48d6ffb0abfc4474984bf2739084fdde9ce185ba592d26c7f446f53ee9c8f07cca4b58848080923eda3c6026c379a5b29b1b8d67324e74469f7

test:
  secret_key_base: b1f1db9b9fc0b23b5d9b9e3fd20bb43098864a3b97b20e88a6c058b786859ce68134cfded30b077e91d098acd661d17b3d9dc90e2f14ab7fae2023bad484358d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
